### PR TITLE
Deleted one line

### PR DESCRIPTION
**Pull request by jbakirov**

### CODE REVIEW

**Review by rustam-umarov — APPROVED** [review]
Line removed!

**Review by rustam-umarov — APPROVED** [review]
Approved, thanks!

**Comment by Sh3R** [comment]
refs/heads/development, protected branch hook declined  
chto za oshibka?

**Comment by jbakirov** [comment]
v development i master branchi nelza delat pushi. nado budet noviy branch otkrit i v nem rabotat, posle sozdat pull request

**Pull request merged**
